language: java
jdk:
  - oraclejdk8

sudo: false
install: true


script:
  - echo $BRANCH
  - 'ls -al'
  - 'cd ./cloud-native-app'
  - 'mvn clean install -DskipTests=false -Dmaven.javadoc.skip=true -B -V'
  - 'cd ./target'
  - 'ls -al'
  - 'cd ../..'
  - 'ls -al'

after_success :
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip ./cloud-native-app/target/cloud-native-app-0.0.1-SNAPSHOT.war infrastructure/aws/codedeploy
  - ls -al
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
    provider : s3
    local_dir : codedeploy_artifact
    bucket : $s3_bucket
    region : us-east-1
    skil_cleanup: true
    access_key_id : $access_key_id
    secret_access_key : $secret_access_key
    on:
      branch: cicd-lab


notifications:
  email:
    recipients:
      - gupta.anu@husky.neu.edu
      - kandpal.d@husky.neu.edu
      - kapse.r@husky.neu.edu
    on_success: always
    on_failure: always
