language: java
jdk:
  - oraclejdk8
sudo: false
install: true
script:
  - pwd
  - 'cd ./cloud-native-app'
  - 'mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
  - 'cd ./target'
  - 'ls -al'
  - 'cd ../..'
  - 'ls -al'
  - pwd
after_success:
  - pwd
  - 'ls -al'
  - 'mkdir codedeploy_artifact'
  -  cp infrastructure/aws/codedeploy/*.sh .
  -  cp infrastructure/aws/codedeploy/*.yml .
  - 'zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip cloud-native-app/target/webapp.war *.sh *.yml'
  - 'ls -al'
  - 'mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/'
  - 'ls -al'
  - pwd
  - 'cd codedeploy_artifact'
  - 'ls -al'
  - pwd
  - 'cd ..'
  - pwd
  - 'ls -al'
deploy:
  -
    provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      all_branches: true
  -
    provider: codedeploy
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: $s3_bucket
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    bundle_type: zip
    application: CSYE6225WebappCodeDeploy
    deployment_group: CSYE6225WebappCodeDeploy
    region: us-east-1
    wait-until-deployed: true
    on:
      all_branches: true


notifications:
  email:
    recipients:
      - gupta.anu@husky.neu.edu
      - kandpal.d@husky.neu.edu
      - kapse.r@husky.neu.edu
    on_failure: always
